/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.6
 * Generated at: 2023-05-11 07:01:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class ArtistLogIn_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("	<head>\r\n");
      out.write("		<link\r\n");
      out.write("			rel=\"apple-touch-icon\"\r\n");
      out.write("			sizes=\"180x180\"\r\n");
      out.write("			href=\"../../resources/apple-touch-icon.png\"\r\n");
      out.write("		/>\r\n");
      out.write("		<link\r\n");
      out.write("			rel=\"icon\"\r\n");
      out.write("			type=\"image/png\"\r\n");
      out.write("			sizes=\"32x32\"\r\n");
      out.write("			href=\"../../resources/favicon-32x32.png\"\r\n");
      out.write("		/>\r\n");
      out.write("		<link\r\n");
      out.write("			rel=\"icon\"\r\n");
      out.write("			type=\"image/png\"\r\n");
      out.write("			sizes=\"16x16\"\r\n");
      out.write("			href=\"../../resources/favicon-16x16.png\"\r\n");
      out.write("		/>\r\n");
      out.write("		<link rel=\"manifest\" href=\"../../resources/site.webmanifest\" />\r\n");
      out.write("		<link rel=\"mask-icon\" href=\"../../resources/safari-pinned-tab.svg\" color=\"#5bbad5\" />\r\n");
      out.write("		<meta name=\"msapplication-TileColor\" content=\"#da532c\" />\r\n");
      out.write("		<meta name=\"theme-color\" content=\"#ffffff\" />\r\n");
      out.write("		<title>Login</title>\r\n");
      out.write("		<meta charset=\"utf-8\" />\r\n");
      out.write("		<meta\r\n");
      out.write("			name=\"viewport\"\r\n");
      out.write("			content=\"width=device-width, initial-scale=1, shrink-to-fit=no\"\r\n");
      out.write("		/>\r\n");
      out.write("\r\n");
      out.write("		<link\r\n");
      out.write("			href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\"\r\n");
      out.write("			rel=\"stylesheet\"\r\n");
      out.write("			integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\"\r\n");
      out.write("			crossorigin=\"anonymous\"\r\n");
      out.write("		/>\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"css/styles.css\" />\r\n");
      out.write("		<script src=\"https://kit.fontawesome.com/36effec9ae.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("		<script src=\"https://unpkg.com/boxicons@2.1.4/dist/boxicons.js\"></script>\r\n");
      out.write("		<title>Login</title>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		<div class=\"customLinearGradient\">\r\n");
      out.write("			<main class=\"loginMain d-flex justify-content-center align-items-lg-center\">\r\n");
      out.write("					<form class=\"form-signin text-center\" action = \"ArtistLogInServlet\">\r\n");
      out.write("					  <img class=\"mb-4\" src=\"./resources/headphones.svg\" alt=\"\" width=\"72\" height=\"72\">\r\n");
      out.write("					  <h1 class=\"h3 mb-3 font-weight-normal myText-love\">Please log in</h1>\r\n");
      out.write("					  		  <label for=\"inputUsername\" class=\"sr-only\">Username</label>\r\n");
      out.write("					  <input type=\"text\" id=\"inputUsername\" class=\"form-control mb-3\" placeholder=\"Username\" name = \"AName\" required autofocus>\r\n");
      out.write("					\r\n");
      out.write("					  <label for=\"inputEmail\" class=\"sr-only\">Email address</label>\r\n");
      out.write("					  <input type=\"email\" id=\"inputEmail\" class=\"form-control mb-3\" placeholder=\"Email address\" name = \"AEmail\" required autofocus>\r\n");
      out.write("					 \r\n");
      out.write("			\r\n");
      out.write("					 \r\n");
      out.write("					  <label for=\"inputPassword\" class=\"sr-only\">Password</label>\r\n");
      out.write("					  <input type=\"password\" id=\"inputPassword\" class=\"form-control mb-3\" placeholder=\"Password\" name = \"APassword\" required> \r\n");
      out.write("					  <button class=\"myBtn-lg\" type=\"submit\">Log In</button>\r\n");
      out.write("					  <div class=\"checkColor mt-3\">\r\n");
      out.write("						  <p>Not a member? <a href=\"ArtistSignUp.jsp\" class=\"myText-love text-decoration-none customHover\">Sign Up</a></p>\r\n");
      out.write("					  </div>\r\n");
      out.write("					</form>\r\n");
      out.write("			</main>\r\n");
      out.write("			<footer class=\"myText-love text-center\">&copy; Melosphere, All Rights Reserved!</footer>	\r\n");
      out.write("		</div>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
